
settings:
  log_level: DEBUG
  log_dir: /var/log/
  opensearch:
    hosts:
      - https://admin:admin@localhost:9200
    use_ssl: True
    verify_certs: False
    ssl_show_warn: False

jobs:
  OpenSearchCommunity:
    type: twitter
    translate: False
    query: "OpenSearch -#NFT -opensea -openseanft"
    ignore:
      username:
        - archivearticles
        - OPENSEARCH2
        - OpenSearch
  
  OpenSearchCon:
    type: twitter
    translate: False
    query: "#OpenSearchCon"
    ignore:
      username:
        - archivearticles
        - OPENSEARCH2
        - OpenSearch